export const API_LIMITS = {
	HITS_PER_MINUTE: 10,
	HITS_PER_MONTH: 10000,
	ASSISTANT_CALLS_PER_DAY: 30,
	ASSISTANT_TOKENS_PER_DAY: 10000,
};

export const ASSISTANT_API_LIMITS = {
	CALLS_PER_DAY: API_LIMITS.ASSISTANT_CALLS_PER_DAY,
	TOKENS_PER_DAY: API_LIMITS.ASSISTANT_TOKENS_PER_DAY,
};
